services:
  bot:
    image: pytato/musicbtw:1.0-dev-bgm
    env_file:
      - ./.env
    networks:
      - backend
    
  lavalink:
    image: fredboat/lavalink:master
    networks:
      - backend
    volumes:
      - ./config/lavalink/application.yml:/opt/Lavalink/application.yml

networks:
  backend:
